---
title: "citik_humains_analyse_moyenne_kh"
author: "khaldoune hilami"
date: "1/27/2021"
output:
  pdf_document: default
  html_document:
    df_print: paged
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Comparaison des données Météo MF et DSK


```{r include=FALSE}
### Définition du répertoire de travail. NB: Il n'y null besoin de préciser le chemin absolu.
### "./" signifie répertoire courant, soit pycitique/R/citik_humains
getwd()
setwd("./")
```

```{r include=FALSE}
### Pour la fonction qqPlot()
require(car)
require(knitr)
```

```{r include=FALSE}
## Import de la donnée comparative météo-France (MF) et darksky (DSK)
### La donnée MF est issue de 42 stations synoptiques réparties sur le territoire nationale
dskdatavg<- read.csv(
  "../../data/donnee_meteo_nationale_comparative/darksky/darksky_moyennes_journalieres_maille_42.csv", 
   header = TRUE, sep = ",", dec = ".")
mfdatavg <- read.csv(
  "../../data/donnee_meteo_nationale_comparative/meteoFrance/mf_moyennes_journalieres_maille_42.csv",
   header = TRUE, sep = ",", dec = ".")
```

## vérification des jeux de donnée
```{r}
ls(dskdatavg)
ls(mfdatavg)
```

## sommaire de la donnée et analyse primaire
```{r}
kable(summary(dskdatavg[c(17,3:10)]))
kable(summary(mfdatavg[c(13,3:4,6:12)]))
```
```{r echo=FALSE}
### Création du template pour la fonction de génération de l'histogramme
weatherHistogram <- function(paramDSK, paramMF, Breaks, paramName, SIunit){
        
        ### Préparation des intervals
        rangeDsk <- range(paramDSK, na.rm = TRUE)
        rangeMf <- range(paramMF, na.rm = TRUE)
        rangeAll <- c(rangeDsk,rangeMf)
        minBreak <- min(rangeAll)
        maxBreak <- max(rangeAll)
        
        #### définition des intervalles
        Brx <- seq(from= minBreak-10, to= maxBreak+10, by=Breaks) ## tient compte des deux distributions
        
        HHdens <- hist(paramDSK, breaks = Brx, plot = F)
        HHylimax <- max(HHdens$density)
        HHylimin <- min(HHdens$density)
        
        ### freq=F => des fréquences relatives et pas des effectifs
        hist(paramDSK, breaks=Brx,
             freq=F, # fréquences
             col="grey",
             main = paste("Moyenne de ",paramName,SIunit," \n entre 1/1/2017 et 5/4/2020 soit 1191 jours"),
             ylab = "densités",
             xlab = paste("Moyenne de ",paramName,SIunit),
             ylim = c(HHylimin+(HHylimin*25),HHylimax+(HHylimax*.25)),
             cex.main = 1.3,
             cex.lab = 1.5,
             cex.axis = 1.5
        )
        
        ### calcul des paramètres pour la fonction lines() à superposer à l'histo
        HHx <- hist(paramMF, breaks = Brx,  plot=F)
        lines(HHx$mids, HHx$density, lwd = 2, col = "green") ### courbe non lissée 
        lines(density(paramMF, na.rm = TRUE), lwd = 2, col = "blue") ### courbe lissée, kernel
        
}

```

```{r echo=FALSE}
### Création du template pour la fonction des tests statistiques
weatherStats <- function(paramDSK, paramMF, paramName, SIunit){
        
        #cat("Test de normalité ",paramName," ",SIunit)
        qqPlot(paramDSK, ylab = paramName)
        qqPlot(paramMF, ylab = paramName)
        # cat("Tests Faits: voir les grahiques dans la case des Plots de Rstudio")
        
        # cat("Shapiro test")
        print( shapiro.test(paramDSK) ) 
        print( shapiro.test(paramMF) ) 
        
        # cat("t.test entre les différentes DSK et MF ",paramName," ",SIunit)
        print(t.test(paramDSK, paramMF))
        
        # cat("fabrication des données pour le test KW ",paramName," ",SIunit)
        dskdf <- data.frame(param=paramDSK, type='dsk')
        mfdf <- data.frame(param=paramMF, type='mf')
        kwdata <- rbind(dskdf,mfdf)
        # cat("Objet de donnée pour KW Fabriqué:\n")
        # cat("Sommaire de la donnée:\n")
        print( summary(kwdata) )
        
        # cat("Kruskal-Wallis test ",paramName," ",SIunit)
        ## ~ signifie : "en fonction de"
        print( kruskal.test(param ~ type, data = kwdata) ) 
        
        # cat("Test de wilcoxon ",paramName," ",SIunit)
        print( wilcox.test(param ~ type, data = kwdata) )
}

```


```{r echo=FALSE}
### Définition des listes des paramètres
templist <- list(dskParam=dskdatavg$temperature, mfParam=mfdatavg$temperature, Breaks=1, paramName='Température', SIunit='C°')
humlist <- list(dskParam=dskdatavg$humidity, mfParam=trunc(mfdatavg$humidite), Breaks=1, paramName='Humidité', SIunit='%')
ptrlist <- list(dskParam=dskdatavg$dewpoint, mfParam=mfdatavg$point_rose, Breaks=1, paramName='Point de rosée', SIunit='C°')
presslist <- list(dskParam=dskdatavg$pressure, mfParam=mfdatavg$press_mer, Breaks=1, paramName='Pression', SIunit='hPa')
vvlist <- list(dskParam=dskdatavg$windspeed, mfParam=mfdatavg$vvent, Breaks=0.5, paramName='Vitesse du vent', SIunit='m/s')
visiblist <- list(dskParam=dskdatavg$visibility, mfParam=mfdatavg$visibilite, Breaks=1, paramName='Visibilité', SIunit='%')
neblist <-list(dskParam=dskdatavg$cloudcover, mfParam=trunc(mfdatavg$nebulosite), Breaks=2, paramName='Nébulosité', SIunit='%')
raflist <- list(dskParam=dskdatavg$windgust, mfParam=mfdatavg$rafale_10min, Breaks=0.5, paramName='rafale de vent sur 10 min', SIunit='m/s')
preciplist01 <- list(dskParam=dskdatavg$precipintensity, mfParam=mfdatavg$precip_01h, Breaks=0.1, paramName='Intensité de précipitation 1h', SIunit='%')
preciplist24 <- list(dskParam=dskdatavg$precipintensitymax, mfParam=mfdatavg$precip_24h, Breaks=0.1, paramName='Intensité de précipitation 24h', SIunit='%')

paramlist <- list(templist, humlist, ptrlist, presslist, vvlist, visiblist, neblist, raflist, preciplist01, preciplist24)
length(paramlist)

```

```{r echo=FALSE}
####### boucle de calcul itératif
### Boucle Principale:

for( param in paramlist) {
        
        #print(param$paramName)
        #'Histogramme du paramètre météo'
        weatherHistogram(param$dskParam, param$mfParam, param$Breaks, param$paramName, param$SIunit)
        
        #'Test des distributions statistiques'
        weatherStats(param$dskParam, param$mfParam, param$paramName, param$SIunit)
}
```

